apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: affnet-staging-ingress
  namespace: affnet-staging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80

