apiVersion: v1
kind: Secret
metadata:
  name: affnet-secrets
  namespace: affnet-staging
type: Opaque
stringData:
  JWT_SECRET: supersecretjwt
  POSTGRES_USER: affnet
  POSTGRES_PASSWORD: affnetpass
  REDIS_PASSWORD: affnetredis
  OPENAI_API_KEY: ""
  STABILITY_API_KEY: ""

